@startuml main
scale 1
title  "UML Class Diagram"
class Main {
	.. Instance Variables ..
	- _n: int 
	- _data: List
	- _answer: List
	.. Instance Methods ..
	+ readData(): None
	+ findAnswer(): None
	+ getAnswer(): List
	+ getN(): int
	+ getData(): List
	+ solve(): None
}
@enduml